name: editor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5

  flutter:
    sdk: flutter

  #ffmpeg_kit_flutter_full: ^4.5.1



  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  file_picker: ^4.6.1
  video_player: ^2.4.5
  google_fonts: ^3.0.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

